### ISSUE TITLE
相比之前的方法，当前工作多了indices_1, self_link_1, inward_ori_index_1, inward_1, outward_1, neighbor_1这些定义？

### ISSUE THREAD

**Issue by RushToNeverLand** [vvhj/TSGCNeXt#8]
请教一下大佬，neighbor是inward和outward的加和，表示的是最终的点的邻接关系？

**Comment by RushToNeverLand** [comment]
以ntu的数据为例(./graph/ntu_rgb_d.py文件)，7-15行的inward、outward以及neighbour定义我现在明白了

但是从17-23行、25-31行的indices_1, self_link_1, inward_ori_index_1, inward_1, outward_1, neighbor_1这些定义是怎么来的呢？

**Comment by RushToNeverLand** [comment]
而且最奇妙的是inward_ori_index_1里面定义的关节并不是左右对称的，请问这是出于什么考虑的呢？

**Comment by RushToNeverLand** [comment]
定义的Graph类里面是只用到了A这个邻接矩阵变量吗？那为什么还要定义A1、A2、A_binary、A_norm、A_binary_K这些个变量呢

**Comment by vvhj** [comment]
您观察的很仔细，这个文件是基于ctrgcn编写的，有一些前人的工作，但是在这里没用到。这些都是不同的拓扑组织形式，代表了图关系的中的子图，用来提供不同的图关系偏执。您可以用用A1、A2、A_binary、A_norm、A_binary_K。目前我没采用这些邻接矩阵变量，只用A，是想证明即使不引入复杂图机制也能很好的学习，您可以在此基础上继续研究！

**Comment by RushToNeverLand** [comment]
好的，非常感谢大佬的回复~
